hosts:
  - hepapi.com

prometheusRules:
  enabled: true
  expiringInfo:
    days: 90
    severity: info
  expiringWarning:
    days: 60
    severity: warning
  expiringCritical:
    days: 30
    severity: critical

prometheus:
  enabled: true
  scrapeInterval: 300s
  scrapeTimeout: 100s

replicaCount: 1

image:
  repository: ghcr.io/dazwilkin/crtsh-exporter
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "crtsh-kubernetes"

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 9090

livenessProbe:
  httpGet:
    path: /healthz
    port: http
readinessProbe:
  httpGet:
    path: /healthz
    port: http

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}
