replicaCount: 2

image:
  repository: localhost:5000/hepapi_case_project
  tag: "0.0.26"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: image-registry-key

nameOverride: "hepapi-case-app"
fullnameOverride: "hepapi-case-app"

serviceAccount:
  create: false
  annotations: {}
  # Mapped from the serviceAccountName in your deployment
  name: "hepapi-case-minikube-service-account"

container:
  command: ["node"]
  args: ["--env-file=/vault/secrets/.env", "server.js"]
  
podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "hepapi-case-role"
  vault.hashicorp.com/agent-inject-secret-.env: "secret/data/myapp/database"
  vault.hashicorp.com/agent-inject-template-.env: |
    {{- with secret "secret/data/myapp/database" -}}
    {{- range $k, $v := .Data.data }}
    {{ $k }}={{ $v }}
    {{- end }}
    {{- end -}}


podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 3000 
  targetPort: 3000 
  
  livenessProbe:
    enabled: true
    path: "/"
    port: 3000
    initialDelaySeconds: 15
    periodSeconds: 10
    
  readinessProbe:
    enabled: true
    path: "/"
    port: 3000
    initialDelaySeconds: 5
    periodSeconds: 5

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: hepapi-case-app.com
      paths:
        - path: /
          pathType: Prefix
  tls: 
    - secretName: hepapi-case-tls
      hosts:
        - hepapi-case-app.com

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 90
  # targetMemoryUtilizationPercentage is omitted as it wasn't in your HPA manifest

tolerations: []
affinity: {}
